// <auto-generated />
using System;
using FoodReddit3_day.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodReddit3_day.Migrations
{
    [DbContext(typeof(FoodForumContext))]
    [Migration("20260420163213_Ingrdient")]
    partial class Ingrdient
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FoodReddit3_day.Models.AiRecipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeneratedRecipe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IngredientsPrompt")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostId")
                        .IsUnique()
                        .HasFilter("[PostId] IS NOT NULL");

                    b.HasIndex("UserId");

                    b.ToTable("AiRecipes");
                });

            modelBuilder.Entity("FoodReddit3_day.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ParentCommentId")
                        .HasColumnType("int");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("FoodReddit3_day.Models.Community", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Communities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Spicy and flavorful dishes from Thailand",
                            Name = "Thai Food"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Sushi, ramen, and delicate flavors",
                            Name = "Japanese Food"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Kimchi, BBQ, and bold spicy dishes",
                            Name = "Korean Food"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Traditional and modern Chinese cuisine",
                            Name = "Chinese Food"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Pasta, pizza, and classic Italian flavors",
                            Name = "Italian Food"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Burgers, fries, and comfort food",
                            Name = "American Food"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Delicious and affordable street eats",
                            Name = "Street Food"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Clean eating and nutritious meals",
                            Name = "Healthy Food"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Plant-based and cruelty-free dishes",
                            Name = "Vegan Food"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Fresh fish, shrimp, and ocean delights",
                            Name = "Seafood"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Smoky grilled meats and BBQ dishes",
                            Name = "BBQ & Grilled"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Sweet treats, cakes, and pastries",
                            Name = "Desserts"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Coffee culture and cozy cafes",
                            Name = "Cafe & Coffee"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Quick and convenient meals",
                            Name = "Fast Food"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Simple and homemade recipes",
                            Name = "Home Cooking"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Luxury and high-end dining experiences",
                            Name = "Fine Dining"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Creative mix of different cuisines",
                            Name = "Fusion Food"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Hot and fiery dishes for spice lovers",
                            Name = "Spicy Food"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Light bites and starters",
                            Name = "Snacks & Appetizers"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Juices, smoothies, and drinks",
                            Name = "Drinks & Beverages"
                        });
                });

            modelBuilder.Entity("FoodReddit3_day.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CommunityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ingredient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommunityId");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("FoodReddit3_day.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("FoodReddit3_day.Models.Vote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CommentId")
                        .HasColumnType("int");

                    b.Property<int?>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("FoodReddit3_day.Models.AiRecipe", b =>
                {
                    b.HasOne("FoodReddit3_day.Models.Post", "SharedPost")
                        .WithOne("AiRecipe")
                        .HasForeignKey("FoodReddit3_day.Models.AiRecipe", "PostId");

                    b.HasOne("FoodReddit3_day.Models.User", "Requester")
                        .WithMany("AiRecipes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Requester");

                    b.Navigation("SharedPost");
                });

            modelBuilder.Entity("FoodReddit3_day.Models.Comment", b =>
                {
                    b.HasOne("FoodReddit3_day.Models.Comment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FoodReddit3_day.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodReddit3_day.Models.User", "Author")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("ParentComment");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("FoodReddit3_day.Models.Post", b =>
                {
                    b.HasOne("FoodReddit3_day.Models.Community", "Community")
                        .WithMany("Posts")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodReddit3_day.Models.User", "Author")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Community");
                });

            modelBuilder.Entity("FoodReddit3_day.Models.Vote", b =>
                {
                    b.HasOne("FoodReddit3_day.Models.Comment", "Comment")
                        .WithMany()
                        .HasForeignKey("CommentId");

                    b.HasOne("FoodReddit3_day.Models.Post", "Post")
                        .WithMany("Votes")
                        .HasForeignKey("PostId");

                    b.HasOne("FoodReddit3_day.Models.User", "User")
                        .WithMany("Votes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FoodReddit3_day.Models.Comment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("FoodReddit3_day.Models.Community", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("FoodReddit3_day.Models.Post", b =>
                {
                    b.Navigation("AiRecipe")
                        .IsRequired();

                    b.Navigation("Comments");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("FoodReddit3_day.Models.User", b =>
                {
                    b.Navigation("AiRecipes");

                    b.Navigation("Comments");

                    b.Navigation("Posts");

                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
